### ISSUE TITLE
How to add more data description to the data portal website?

### ISSUE THREAD

**Issue by Sheldon-Zhang** [smda/smart-meter-data-catalog#5]
How can I add more description of Gatech EV data analytics to the website?
Currently, it's only one line explanation.
https://smda.github.io/smart-meter-data-portal/

**Comment by RSLi** [comment]
Hi Sheldon! Thanks for using the portal. In response to your feedback, I've updated the form to support multi-line descriptions. Note that you can also provide more detailed description in the `README.md` file in the repository you provide (since you are using Github, in this case, and this is highly encouraged).

(The original design is to encourage short descriptions on the website and long descriptions in the README or website that the submitted item is linked to, but I still changes the form to support multi-line for users who want to quickly copy paste existing descriptions). 

If you want to update your submission, feel free to use this [link](https://github.com/smda/smart-meter-data-catalog/edit/master/items/Gatech%20EV%20Data%20Analytics) and submit a request as you did before. You can either fill out the form again, or just edit the generated code.

 eg. `description: "This is a \nmulti-line description"`

Best regards
